import test from "node:test";
import assert from "node:assert/strict";
import { generateContentSuggestions, stripHtmlForContentPreview } from "../lib/audit-engine";

test("stripHtmlForContentPreview removes nested tags and decodes entities", () => {
  assert.equal(stripHtmlForContentPreview("<span>Hello &amp; <b>world</b></span>"), "Hello & world");
  assert.equal(stripHtmlForContentPreview(""), "");
});

test("content suggestions use actionable categories", () => {
  const html = `<!DOCTYPE html><html><head><title>TechShala</title></head><body>
    <h1><span class="x">Build skills <strong>together</strong></span></h1>
  </body></html>`;
  const rows = generateContentSuggestions(html, "other", 55);
  const kinds = rows.map((r) => r.type).sort();
  assert.deepEqual(kinds, ["contentClarity", "conversionPath", "trustAndProof"].sort());
  assert.ok(rows.every((r) => !r.current.includes("<")));
});

test("low-confidence neutral path avoids heavy sales or revenue framing", () => {
  const html = "<html><head><title>Local Club</title><meta name='description' content='We meet weekly.'/></head><body><h1>Home</h1><p>Welcome.</p></body></html>";
  const rows = generateContentSuggestions(html, "other", 48);
  const joined = rows.map((r) => `${r.suggested} ${r.reason}`).join(" ");
  assert.ok(!/revenue|conversion-focused|buy now/i.test(joined));
});

test("education/community content avoids hard sales claims in suggestions", () => {
  const html = `<html><head><title>TechShala — Home</title>
    <meta name="description" content="Learn together"/></head><body>
    <h1>Welcome</h1>
    <p>Join our community courses and workshops for students.</p>
  </body></html>`;
  const rows = generateContentSuggestions(html, "other", 60);
  const joined = rows.map((r) => `${r.suggested} ${r.reason}`).join(" ");
  assert.ok(!/buy now|hard sell|instant revenue/i.test(joined));
  assert.ok(/content|conversion|trust|proof|audience|service/i.test(joined));
});

test("confidence is computed and identical for the same inputs", () => {
  const html = "<html><head><title>Acme</title><meta name='description' content='We build widgets.'/></head><body><h1>Widgets</h1></body></html>";
  const a = generateContentSuggestions(html, "saas", 80);
  const b = generateContentSuggestions(html, "saas", 80);
  assert.deepEqual(
    a.map((x) => x.confidence),
    b.map((x) => x.confidence)
  );
  assert.ok(a.every((x) => x.confidence >= 0 && x.confidence <= 100));
});

test("error page content is sanitized and suggestions switch to recovery guidance", () => {
  const html = `
    <html>
      <head>
        <title>ERROR: The request could not be satisfied</title>
      </head>
      <body>
        <h1>403 ERROR</h1>
        <p>The request could not be satisfied. Generated by cloudfront.</p>
      </body>
    </html>
  `;

  const rows = generateContentSuggestions(html, "other", 55);

  assert.ok(rows.every((r) => r.current === "Missing"));
  assert.ok(rows.every((r) => !/error/i.test(r.suggested)));
  assert.ok(rows.every((r) => /could not be audited|unavailable|could not read/i.test(r.suggested)));
  assert.ok(rows.every((r) => r.confidence >= 0 && r.confidence <= 40));
});

test("normal page with the word error does not trigger error-page fallback", () => {
  const html = `
    <html>
      <head>
        <title>Debugging Guide | Acme Docs</title>
        <meta name="description" content="Learn error handling patterns for robust apps." />
      </head>
      <body>
        <h1>Error handling in JavaScript</h1>
        <p>This page explains try/catch, retries, and observability.</p>
      </body>
    </html>
  `;

  const rows = generateContentSuggestions(html, "other", 60);
  assert.ok(rows.some((r) => r.current !== "Missing"));
  assert.ok(rows.every((r) => !/could not be audited right now|page unavailable during scan/i.test(r.suggested)));
});

test("degraded fallback marker triggers recovery guidance", () => {
  const html = `
    <html>
      <head><title>https://example.com</title></head>
      <body><main>degraded-fallback</main></body>
    </html>
  `;
  const rows = generateContentSuggestions(html, "other", 45);
  assert.ok(rows.every((r) => r.current === "Missing"));
  assert.ok(rows.every((r) => /could not be audited|unavailable|could not read/i.test(r.suggested)));
});