import test from "node:test";
import assert from "node:assert/strict";
import { generateContentSuggestions, stripHtmlForContentPreview } from "../lib/audit-engine";

test("stripHtmlForContentPreview removes nested tags and decodes entities", () => {
  assert.equal(stripHtmlForContentPreview("<span>Hello &amp; <b>world</b></span>"), "Hello & world");
  assert.equal(stripHtmlForContentPreview(""), "");
});

test("H1 current value is plain text without markup", () => {
  const html = `<!DOCTYPE html><html><head><title>TechShala</title></head><body>
    <h1><span class="x">Build skills <strong>together</strong></span></h1>
  </body></html>`;
  const rows = generateContentSuggestions(html, "other", 55);
  const h1 = rows.find((r) => r.type === "h1");
  assert.ok(h1);
  assert.equal(h1!.current, "Build skills together");
  assert.ok(!h1!.current.includes("<"));
});

test("low-confidence neutral path avoids heavy sales or revenue framing", () => {
  const html = "<html><head><title>Local Club</title><meta name='description' content='We meet weekly.'/></head><body><h1>Home</h1><p>Welcome.</p></body></html>";
  const rows = generateContentSuggestions(html, "other", 48);
  const joined = rows.map((r) => `${r.suggested} ${r.reason}`).join(" ");
  assert.ok(!/revenue|conversion-focused|buy now/i.test(joined));
});

test("education and community signals produce non-salesy suggestions", () => {
  const html = `<html><head><title>TechShala — Home</title>
    <meta name="description" content="Learn together"/></head><body>
    <h1>Welcome</h1>
    <p>Join our community courses and workshops for students.</p>
  </body></html>`;
  const rows = generateContentSuggestions(html, "other", 60);
  const title = rows.find((r) => r.type === "title");
  assert.ok(title);
  assert.ok(/course|workshop|community|learn/i.test(title!.suggested));
  assert.ok(!/leads|revenue|conversion/i.test(title!.suggested));
  assert.ok(/education|community|learning|participation/i.test(title!.reason));
});

test("confidence is computed and identical for the same inputs", () => {
  const html = "<html><head><title>Acme</title><meta name='description' content='We build widgets.'/></head><body><h1>Widgets</h1></body></html>";
  const a = generateContentSuggestions(html, "saas", 80);
  const b = generateContentSuggestions(html, "saas", 80);
  assert.deepEqual(
    a.map((x) => x.confidence),
    b.map((x) => x.confidence)
  );
  assert.ok(a.every((x) => x.confidence >= 0 && x.confidence <= 100));
});

test("error page content is sanitized and suggestions switch to recovery guidance", () => {
  const html = `
    <html>
      <head>
        <title>ERROR: The request could not be satisfied</title>
      </head>
      <body>
        <h1>403 ERROR</h1>
        <p>The request could not be satisfied. Generated by cloudfront.</p>
      </body>
    </html>
  `;

  const rows = generateContentSuggestions(html, "other", 55);

  assert.ok(rows.every((r) => r.current === "Missing"));
  assert.ok(rows.every((r) => !/error/i.test(r.suggested)));
  assert.ok(rows.every((r) => /could not be audited|unavailable|could not read/i.test(r.suggested)));
  assert.ok(rows.every((r) => r.confidence >= 0 && r.confidence <= 40));
});

test("normal page with the word error does not trigger error-page fallback", () => {
  const html = `
    <html>
      <head>
        <title>Debugging Guide | Acme Docs</title>
        <meta name="description" content="Learn error handling patterns for robust apps." />
      </head>
      <body>
        <h1>Error handling in JavaScript</h1>
        <p>This page explains try/catch, retries, and observability.</p>
      </body>
    </html>
  `;

  const rows = generateContentSuggestions(html, "other", 60);
  assert.ok(rows.some((r) => r.current !== "Missing"));
  assert.ok(rows.every((r) => !/could not be audited right now|page unavailable during scan/i.test(r.suggested)));
});

test("service-company title is not rewritten into generic ecommerce headline", () => {
  const html = `
    <html>
      <head>
        <title>Hertzsoft Technologies | Web & Mobile App Development Company in Mumbai</title>
        <meta name="description" content="Custom web and mobile app development services in Mumbai." />
      </head>
      <body>
        <h1>Web and Mobile App Development Services</h1>
        <p>We build software products for startups and enterprises.</p>
      </body>
    </html>
  `;

  const rows = generateContentSuggestions(html, "ecommerce", 88);
  const title = rows.find((r) => r.type === "title");
  const meta = rows.find((r) => r.type === "metaDescription");
  const h1 = rows.find((r) => r.type === "h1");
  assert.ok(title);
  assert.ok(meta);
  assert.ok(h1);
  assert.ok(!/top ecommerce website/i.test(title!.suggested));
  assert.ok(/hertzsoft|web|mobile app|development|mumbai/i.test(title!.suggested));
  assert.ok(!/explain your offer/i.test(meta!.suggested));
  assert.ok(/hertzsoft|development|mumbai/i.test(meta!.suggested));
  assert.ok(!/a clear headline:/i.test(h1!.suggested));
  assert.ok(/hertzsoft|web|mobile app|development|mumbai/i.test(h1!.suggested));
});

test("same-but-better policy keeps strong title and h1 close to original wording", () => {
  const html = `
    <html>
      <head>
        <title>Hertzsoft Technologies | Web & Mobile App Development Company in Mumbai</title>
        <meta name="description" content="Hertzsoft Technologies: Mumbai" />
      </head>
      <body>
        <h1>Transform Your Business With Cutting-Edge Software Solutions</h1>
      </body>
    </html>
  `;

  const rows = generateContentSuggestions(html, "ecommerce", 90);
  const title = rows.find((r) => r.type === "title");
  const meta = rows.find((r) => r.type === "metaDescription");
  const h1 = rows.find((r) => r.type === "h1");

  assert.ok(title && meta && h1);
  assert.ok(overlap(title!.current, title!.suggested) >= 0.6);
  assert.ok(overlap(h1!.current, h1!.suggested) >= 0.5);
  assert.ok(meta!.suggested.length > meta!.current.length);
  assert.ok(/hertzsoft|development|mumbai/i.test(meta!.suggested));
});

function overlap(a: string, b: string): number {
  const tokenize = (s: string) =>
    new Set(
      s
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, " ")
        .split(/\s+/)
        .filter((w) => w.length >= 4)
    );
  const A = tokenize(a);
  const B = tokenize(b);
  if (!A.size || !B.size) return 0;
  let inter = 0;
  for (const x of A) if (B.has(x)) inter++;
  return inter / A.size;
}
