import { AUDIT_PROMPTS, COLOR_PSYCHOLOGY_TIPS } from "./prompts";

export type AuditScores = {
  uiux: number;
  perf: number;
  mobile: number;
  access: number;
  seo: number;
  leads: number;
  overall: number;
};

export type AuditResult = {
  scores: AuditScores;
  issues: string[];
  fixes: string[];
  leadBoost: string;
  benchmark: { you: number; competitorsAvg: number };
  promptsUsed: typeof AUDIT_PROMPTS;
  colorSuggestions: string[];
};

export type ContentSuggestion = {
  type: "contentClarity" | "conversionPath" | "trustAndProof";
  current: string;
  suggested: string;
  reason: string;
  confidence: number;
  guidelineBullets: string[];
};

/** Exported for tests — strips tags/entities from a fragment (e.g. first H1 inner HTML). */
export function stripHtmlForContentPreview(fragment: string): string {
  let s = String(fragment || "");
  s = s.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ");
  let prev = "";
  while (prev !== s) {
    prev = s;
    s = s.replace(/<[^>]+>/g, " ");
  }
  s = decodeHtmlEntities(s);
  return s.replace(/\s+/g, " ").trim();
}

function decodeHtmlEntities(s: string): string {
  return s
    .replace(/&nbsp;/gi, " ")
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => {
      const cp = parseInt(h, 16);
      return Number.isFinite(cp) ? String.fromCodePoint(cp) : _;
    })
    .replace(/&#(\d+);/g, (_, d) => {
      const cp = parseInt(d, 10);
      return Number.isFinite(cp) ? String.fromCodePoint(cp) : _;
    })
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function normalizeContentField(stripped: string): string {
  const t = stripped.trim();
  return t.length > 0 ? t : "Missing";
}

function isErrorLikeText(value: string): boolean {
  const t = String(value || "").toLowerCase();
  if (!t || t === "missing") return false;
  return /(^\s*(error[:-]|403|404|429|500|502|503)\b|\b\d{3}\s+error\b|request could not be satisfied|generated by cloudfront|access denied|\bforbidden\b|service unavailable|temporarily unavailable|\bnot found\b|degraded-fallback)/i.test(
    t
  );
}

function isLikelyErrorPage(html: string): boolean {
  const plain = stripHtmlForContentPreview(String(html || "")).toLowerCase();
  if (plain.includes("degraded-fallback")) return true;
  const hardSignals = [
    "request could not be satisfied",
    "generated by cloudfront",
    "access denied",
    "forbidden",
    "not found",
    "service unavailable",
    "temporarily unavailable",
    "degraded-fallback",
  ];
  const hardSignalCount = hardSignals.reduce((acc, s) => acc + (plain.includes(s) ? 1 : 0), 0);
  const hasStatusWithErrorWord = /\b(403|404|429|500|502|503)\b\s*(error|forbidden|not found|bad gateway|service unavailable)?/i.test(plain);

  // Require stronger evidence to avoid false positives on regular pages.
  if (hardSignalCount >= 2) return true;
  if (hardSignalCount >= 1 && hasStatusWithErrorWord) return true;
  return false;
}

function sanitizeCurrentField(value: string): string {
  if (value === "Missing") return value;
  return isErrorLikeText(value) ? "Missing" : value;
}

function extractBrandHint(title: string): string | null {
  if (!title || title === "Missing") return null;
  if (isErrorLikeText(title)) return null;
  const part = title.split(/\s*[|\u2013\-–:]\s*/)[0].trim();
  if (part.length >= 2 && part.length <= 48) return part;
  return null;
}

function compactSpaces(text: string): string {
  return String(text || "").replace(/\s+/g, " ").trim();
}

function trimWords(text: string, maxWords: number): string {
  const words = compactSpaces(text).split(" ").filter(Boolean);
  return words.slice(0, maxWords).join(" ");
}

function trimChars(text: string, maxChars: number): string {
  const t = compactSpaces(text);
  if (t.length <= maxChars) return t;
  return t.slice(0, Math.max(0, maxChars - 1)).trimEnd() + "...";
}

function toSentenceCase(text: string): string {
  const t = compactSpaces(text);
  if (!t) return "";
  return t.charAt(0).toUpperCase() + t.slice(1);
}

function buildTopicPhrase(values: string[]): string {
  const stop = new Set([
    "the",
    "and",
    "for",
    "with",
    "your",
    "this",
    "that",
    "from",
    "home",
    "welcome",
    "page",
    "company",
    "best",
    "top",
    "official",
  ]);

  const joined = values
    .filter((v) => v && v !== "Missing" && !isErrorLikeText(v))
    .join(" ")
    .toLowerCase()
    .replace(/[^a-z0-9\s&-]/g, " ");

  const unique: string[] = [];
  for (const raw of joined.split(/\s+/)) {
    const token = raw.trim();
    if (!token || token.length < 3 || stop.has(token)) continue;
    if (!unique.includes(token)) unique.push(token);
    if (unique.length >= 7) break;
  }
  return compactSpaces(unique.join(" "));
}

function industrySignalPresent(html: string, industry: string): boolean {
  const t = html.toLowerCase();
  const checks: Record<string, RegExp> = {
    ecommerce: /\b(ecommerce|store|shop|product|cart|checkout|sku)\b/i,
    saas: /\b(saas|software|platform|subscription|free trial|book demo|request demo)\b/i,
    local_service: /\b(service area|near me|book appointment|get quote|call now)\b/i,
    agency: /\b(agency|studio|portfolio|case studies|client work)\b/i,
    media: /\b(news|editorial|breaking|opinion|subscribe)\b/i,
    nonprofit: /\b(nonprofit|donate|volunteer|mission|charity)\b/i,
    manufacturing: /\b(manufacturing|industrial|factory|automation|supply chain)\b/i,
    other: /$^/,
  };
  const re = checks[industry] || checks.other;
  return re.test(t);
}

type ContentIntentTier = "commercial" | "education_community" | "neutral";

function scoreEducationSignals(html: string): number {
  const t = html.toLowerCase();
  const terms = [
    "course",
    "courses",
    "curriculum",
    "workshop",
    "cohort",
    "community",
    "student",
    "students",
    "learn",
    "learning",
    "tutorial",
    "academy",
    "bootcamp",
    "syllabus",
    "certificate",
    "mentor",
    "meetup",
    "scholarship",
  ];
  let score = 0;
  for (const w of terms) {
    if (t.includes(w)) score += 8;
  }
  if (/\b(nonprofit|volunteer|donate)\b/i.test(html)) score += 14;
  return Math.min(100, score);
}

function scoreCommercialSignals(html: string, industry: string): number {
  if (industry === "ecommerce") return 100;
  const t = html.toLowerCase();
  let score = industry === "saas" ? 28 : 0;
  const terms = ["add to cart", "checkout", "buy now", "pricing", "subscribe now", "free trial", "request demo", "book a demo", "get quote"];
  for (const w of terms) {
    if (t.includes(w)) score += 22;
  }
  return Math.min(100, score);
}

function resolveContentIntentTier(html: string, industry: string): {
  tier: ContentIntentTier;
  eduScore: number;
  commercialScore: number;
} {
  const eduScore = scoreEducationSignals(html);
  const commercialScore = scoreCommercialSignals(html, industry);
  if (industry === "nonprofit") {
    return { tier: "education_community", eduScore: Math.max(eduScore, 40), commercialScore };
  }
  if (commercialScore >= 50 && commercialScore >= eduScore + 12) {
    return { tier: "commercial", eduScore, commercialScore };
  }
  if (eduScore >= 24 || industry === "nonprofit") {
    return { tier: "education_community", eduScore, commercialScore };
  }
  return { tier: "neutral", eduScore, commercialScore };
}

function intentClarityForConfidence(eduScore: number, commercialScore: number): number {
  const gap = Math.abs(eduScore - commercialScore);
  return Math.min(100, Math.round(42 + gap * 0.45));
}

function fieldEvidenceQuality(current: string, kind: "title" | "metaDescription" | "h1"): { present: boolean; quality: number } {
  if (!current || current === "Missing") return { present: false, quality: 0 };
  const hasTag = /[<>]/.test(current);
  let quality = 88;
  if (hasTag) quality -= 48;
  const len = current.length;
  if (kind === "title") {
    if (len < 12) quality -= 22;
    if (len > 70) quality -= 12;
  } else if (kind === "metaDescription") {
    if (len < 40) quality -= 18;
    if (len > 320) quality -= 14;
  } else {
    if (len < 6) quality -= 20;
    if (len > 120) quality -= 10;
  }
  return { present: true, quality: Math.max(0, Math.min(100, Math.round(quality))) };
}

function computeContentSuggestionConfidence(input: {
  industryConfidence: number;
  fieldPresent: boolean;
  fieldQuality: number;
  intentClarity: number;
  tierAlignmentBonus: number;
  errorPageDetected?: boolean;
}): number {
  const base =
    input.industryConfidence * 0.28 +
    input.fieldQuality * 0.32 +
    input.intentClarity * 0.28 +
    input.tierAlignmentBonus;
  let v = Math.round(base);
  if (!input.fieldPresent) v -= 14;
  if (input.errorPageDetected) v -= 35;
  return Math.max(0, Math.min(100, v));
}

function scoreFromSignals(base: number, bonuses: number[], penalties: number[]) {
  const value = base + bonuses.reduce((a, b) => a + b, 0) - penalties.reduce((a, b) => a + b, 0);
  return Math.max(0, Math.min(100, Math.round(value)));
}

function count(html: string, regex: RegExp) {
  return (html.match(regex) || []).length;
}

export function analyzeWebsite(htmlRaw: string, pagespeedRaw: any): AuditResult {
  const html = String(htmlRaw || "").toLowerCase();
  const metrics = pagespeedRaw?.lighthouseResult?.audits ?? {};
  const perfScore = pagespeedRaw?.lighthouseResult?.categories?.performance?.score;

  const hasViewport = /<meta[^>]*name=["']viewport["']/i.test(html);
  const formCount = count(html, /<form[\s>]/gi);
  const ctaCount = count(html, /(get started|book demo|contact us|sign up|try free|request demo)/gi);
  const h1Count = count(html, /<h1[\s>]/gi);
  const headings = count(html, /<h[1-6][\s>]/gi);
  const altCount = count(html, /<img[^>]*alt=["'][^"']+/gi);
  const imgCount = count(html, /<img[\s>]/gi);
  const ariaCount = count(html, /\saria-[a-z-]+=/gi);
  const navCount = count(html, /<nav[\s>]/gi);
  const titleTag = /<title>.+<\/title>/i.test(html);
  const metaDesc = /<meta[^>]*name=["']description["'][^>]*>/i.test(html);
  const hasCanonical = /<link[^>]*rel=["']canonical["']/i.test(html);

  const lcp = metrics["largest-contentful-paint"]?.numericValue ?? 3500;
  const cls = metrics["cumulative-layout-shift"]?.numericValue ?? 0.18;
  const tbt = metrics["total-blocking-time"]?.numericValue ?? 280;

  const uiux = scoreFromSignals(
    65,
    [navCount > 0 ? 10 : 0, ctaCount > 0 ? 8 : 0, headings >= 5 ? 8 : 0],
    [h1Count === 0 ? 10 : 0, ctaCount === 0 ? 10 : 0]
  );

  const perf = scoreFromSignals(
    typeof perfScore === "number" ? perfScore * 100 : 55,
    [lcp < 2500 ? 10 : 0, cls < 0.1 ? 8 : 0, tbt < 200 ? 8 : 0],
    [lcp > 4000 ? 12 : 0, cls > 0.25 ? 10 : 0, tbt > 600 ? 10 : 0]
  );

  const mobile = scoreFromSignals(
    60,
    [hasViewport ? 20 : 0, ctaCount > 0 ? 6 : 0],
    [!hasViewport ? 20 : 0, headings < 3 ? 6 : 0]
  );

  const access = scoreFromSignals(
    58,
    [imgCount > 0 ? Math.min(20, Math.round((altCount / imgCount) * 20)) : 12, ariaCount > 2 ? 10 : 0],
    [imgCount > 0 && altCount / imgCount < 0.7 ? 12 : 0]
  );

  const seo = scoreFromSignals(
    62,
    [titleTag ? 12 : 0, metaDesc ? 10 : 0, hasCanonical ? 8 : 0, h1Count === 1 ? 6 : 0],
    [!titleTag ? 15 : 0, !metaDesc ? 12 : 0, h1Count > 1 ? 6 : 0]
  );

  const leads = scoreFromSignals(
    50,
    [formCount > 0 ? 20 : 0, ctaCount > 0 ? 20 : 0],
    [formCount === 0 ? 15 : 0, ctaCount === 0 ? 15 : 0]
  );

  const overall = Math.round(
    uiux * 0.25 + perf * 0.2 + mobile * 0.2 + access * 0.15 + seo * 0.15 + leads * 0.05
  );
  const leadBoost = `${Math.round((100 - overall) * 0.3)}%`;

  const issues: string[] = [];
  const fixes: string[] = [];

  if (!hasViewport) {
    issues.push("Missing mobile viewport meta tag.");
    fixes.push('Add `<meta name="viewport" content="width=device-width, initial-scale=1" />`.');
  }
  if (!titleTag || !metaDesc) {
    issues.push("SEO metadata is incomplete.");
    fixes.push("Add unique title + meta description per primary landing page.");
  }
  if (imgCount > 0 && altCount / imgCount < 0.7) {
    issues.push("Many images are missing descriptive alt text.");
    fixes.push("Provide meaningful alt text for all informative images.");
  }
  if (lcp > 4000 || tbt > 600) {
    issues.push("Performance metrics indicate heavy render workload.");
    fixes.push("Compress hero media, defer non-critical JS, and inline critical CSS.");
  }
  if (formCount === 0) {
    issues.push("No lead capture form found.");
    fixes.push("Add above-the-fold lead form with 1 primary CTA.");
  }
  if (ctaCount === 0) {
    issues.push("No clear conversion CTA detected.");
    fixes.push('Add repeated CTA labels like "Book Demo" and "Start Free Trial".');
  }
  if (h1Count !== 1) {
    issues.push("Heading hierarchy is weak (expect exactly one H1).");
    fixes.push("Use one descriptive H1 and structured H2/H3 sections.");
  }

  const competitorsAvg = Math.max(35, Math.min(95, overall - 8 + (overall % 13)));

  return {
    scores: { uiux, perf, mobile, access, seo, leads, overall },
    issues,
    fixes,
    leadBoost,
    benchmark: { you: overall, competitorsAvg },
    promptsUsed: AUDIT_PROMPTS,
    colorSuggestions: COLOR_PSYCHOLOGY_TIPS,
  };
}

export function generateContentSuggestions(htmlRaw: string, industry: string, industryConfidence: number): ContentSuggestion[] {
  const html = String(htmlRaw || "");
  const plain = stripHtmlForContentPreview(html).toLowerCase();
  const errorPageDetected = isLikelyErrorPage(html);

  const formCount = (html.match(/<form[\s>]/gi) || []).length;
  const ctaCount =
    (plain.match(/\b(book demo|get started|contact us|call now|request quote|start free trial|get quote|talk to us|schedule call)\b/gi) || [])
      .length;
  const proofCount =
    (plain.match(/\b(testimonial|client|case stud|portfolio|review|rating|trusted by|award|certified|experience)\b/gi) || []).length;
  const serviceKeywordCount =
    (plain.match(/\b(web development|mobile app|crm|erp|pos|shopify|wordpress|digital marketing|seo|ai|machine learning)\b/gi) || [])
      .length;

  const clarityConfidence = Math.max(45, Math.min(96, Math.round(industryConfidence * 0.55 + serviceKeywordCount * 5)));
  const conversionConfidence = Math.max(40, Math.min(95, Math.round(industryConfidence * 0.45 + ctaCount * 10 + formCount * 12)));
  const trustConfidence = Math.max(38, Math.min(94, Math.round(industryConfidence * 0.5 + proofCount * 8)));

  const industryLabel = industry.replace(/_/g, " ");

  if (errorPageDetected) {
    return [
      {
        type: "contentClarity",
        current: "Page content could not be reliably read.",
        suggested: "Fix page access/CDN restrictions and rerun content analysis.",
        reason: "The scan detected an error/blocked response, so content recommendations are conservative.",
        confidence: 30,
        guidelineBullets: [
          "Verify URL and access permissions.",
          "Allow crawler traffic via CDN/firewall rules.",
          "Rerun audit after successful live render.",
        ],
      },
      {
        type: "conversionPath",
        current: "Conversion flow not measurable from current response.",
        suggested: "Revalidate hero CTA + contact form placement after fetch succeeds.",
        reason: "Conversion guidance requires real page content, not error pages.",
        confidence: 28,
        guidelineBullets: ["Place one primary CTA above the fold.", "Keep contact form short (3-5 fields).", "Repeat CTA at section breaks."],
      },
      {
        type: "trustAndProof",
        current: "Trust elements could not be evaluated.",
        suggested: "Re-check testimonials, case studies, and client proof once page is accessible.",
        reason: "Trust analysis needs full page content and visible proof blocks.",
        confidence: 28,
        guidelineBullets: ["Add recognizable client logos.", "Add 2-3 short proof-driven case studies.", "Display social proof near CTA."],
      },
    ];
  }

  return [
    {
      type: "contentClarity",
      current:
        serviceKeywordCount >= 3
          ? `Service messaging is visible (${serviceKeywordCount} key service signals detected).`
          : "Service messaging is generic or scattered.",
      suggested:
        serviceKeywordCount >= 3
          ? `Reframe hero and section intros around one primary offer + one supporting offer for ${industryLabel}.`
          : `Add a clear service stack headline (what you deliver, for whom, and expected outcome) for ${industryLabel} visitors.`,
      reason: "This suggestion is based on actual service/solution phrases found in page copy, not just metadata tags.",
      confidence: clarityConfidence,
      guidelineBullets: [
        "Lead with business outcome, not feature list.",
        "Keep first screen focused on one main offer.",
        "Use short proof-backed service blocks.",
      ],
    },
    {
      type: "conversionPath",
      current:
        formCount > 0 && ctaCount >= 2
          ? `Conversion signals are present (forms: ${formCount}, CTA phrases: ${ctaCount}).`
          : `Weak conversion path (forms: ${formCount}, CTA phrases: ${ctaCount}).`,
      suggested:
        formCount === 0
          ? "Add a visible lead form near the primary CTA and repeat CTA in each major section."
          : "Strengthen CTA hierarchy: one primary CTA + one secondary CTA, with consistent labels across the page.",
      reason: "Built from detected CTA wording and form presence across the rendered page content.",
      confidence: conversionConfidence,
      guidelineBullets: [
        "Keep one primary conversion goal per page.",
        "Use action-oriented CTA copy.",
        "Reduce friction in inquiry/contact forms.",
      ],
    },
    {
      type: "trustAndProof",
      current:
        proofCount >= 3
          ? `Trust/proof elements are visible (${proofCount} trust indicators found).`
          : "Trust signals are limited or not prominent.",
      suggested:
        proofCount >= 3
          ? "Move strongest proof (case result, client logos, testimonial) closer to first CTA."
          : "Add concrete proof blocks: client logos, mini case studies, and testimonial snippets near conversion sections.",
      reason: "Derived from proof-related terms in content (case studies, testimonials, client references).",
      confidence: trustConfidence,
      guidelineBullets: [
        "Show measurable outcomes where possible.",
        "Place trust proof near decision points.",
        "Keep testimonials short and specific.",
      ],
    },
  ];
}